<?php
// ==========================================================
// BLACK HABIT - CREATE ORDER API
// ==========================================================
// DINE-IN:
//   Login NOT required
//   user_id can be NULL
//
// PICK-UP ORDER:
//   Login REQUIRED
//   user_id must be provided
//   Stored in database as "Advance Order"
//
// IMPORTANT:
//   Inventory is NOT deducted here.
//   Inventory is deducted only when cashier marks order READY.
// ==========================================================

header("Access-Control-Allow-Origin: *");
header("Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With");
header("Access-Control-Allow-Methods: POST, OPTIONS");
header("Content-Type: application/json; charset=UTF-8");

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    http_response_code(204);
    exit;
}

ini_set('display_errors', '0');
error_reporting(0);

require_once __DIR__ . "/db.php";

if (ob_get_level()) {
    ob_clean();
}

// ==========================================================
// DATABASE CHECK
// ==========================================================

if (!isset($conn) || !$conn) {
    echo json_encode([
        "success" => false,
        "message" => "Database connection failed."
    ]);
    exit;
}

// ==========================================================
// HELPER FUNCTIONS
// ==========================================================

function tableExistsBH($conn, $table)
{
    $table = mysqli_real_escape_string($conn, $table);

    $result = mysqli_query(
        $conn,
        "SHOW TABLES LIKE '$table'"
    );

    return $result && mysqli_num_rows($result) > 0;
}

function columnExistsBH($conn, $table, $column)
{
    if (!tableExistsBH($conn, $table)) {
        return false;
    }

    $table = mysqli_real_escape_string($conn, $table);
    $column = mysqli_real_escape_string($conn, $column);

    $result = mysqli_query(
        $conn,
        "SHOW COLUMNS FROM `$table` LIKE '$column'"
    );

    return $result && mysqli_num_rows($result) > 0;
}

function findColumnBH($conn, $table, $columns)
{
    foreach ($columns as $column) {
        if (columnExistsBH($conn, $table, $column)) {
            return $column;
        }
    }

    return null;
}

function qtyBH($value)
{
    $value = (float)$value;

    if ($value < 0) {
        return 0;
    }

    return $value;
}

// Maximum quantity allowed for one product in one order.
const MAX_PRODUCT_QUANTITY_BH = 100;

function normalizeSizeBH($size)
{
    $size = strtolower(trim((string)$size));

    if ($size === 'large' || $size === 'l') {
        return 'large';
    }

    return 'regular';
}

function displaySizeBH($size)
{
    return normalizeSizeBH($size) === 'large'
        ? 'Large'
        : 'Regular';
}

function jsonErrorBH($message, $extra = [])
{
    echo json_encode(
        array_merge(
            [
                "success" => false,
                "message" => $message
            ],
            $extra
        ),
        JSON_UNESCAPED_UNICODE |
        JSON_UNESCAPED_SLASHES
    );

    exit;
}

// ==========================================================
// ONLY POST
// ==========================================================

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    jsonErrorBH("POST request required.");
}

// ==========================================================
// READ JSON
// ==========================================================

$rawInput = file_get_contents("php://input");

$data = json_decode($rawInput, true);

if (!is_array($data)) {
    jsonErrorBH("Invalid JSON request.");
}

// ==========================================================
// GET DATA
// ==========================================================

$user_id = $data['user_id'] ?? null;

$order_type = trim(
    (string)($data['order_type'] ?? '')
);

// Client total is accepted only as an informational value.
// The authoritative order total is recalculated from database prices below.
$client_total = isset($data['total'])
    ? (float)$data['total']
    : 0;

$total = 0.0;

$payment_method = trim(
    (string)($data['payment_method'] ?? '')
);

$payment_type = trim(
    (string)($data['payment_type'] ?? '')
);

$paid_amount = isset($data['paid_amount'])
    ? (float)$data['paid_amount']
    : 0;

$balance = isset($data['balance'])
    ? (float)$data['balance']
    : 0;

// Receipt/order number is generated by the server after the order ID is created.
$receipt_number = "";

$items = $data['items'] ?? [];

// Optional FCM token
$fcm_token = trim(
    (string)($data['fcm_token'] ?? '')
);

// ==========================================================
// NORMALIZE USER ID
// ==========================================================

if (
    $user_id === null ||
    $user_id === '' ||
    (int)$user_id <= 0
) {
    $user_id = null;
} else {
    $user_id = (int)$user_id;
}

// ==========================================================
// VALIDATE ORDER TYPE
// ==========================================================

if ($order_type === '') {
    jsonErrorBH("Order type is required.");
}

// ==========================================================
// NORMALIZE ORDER TYPE
// ==========================================================

// Flutter may send:
// Pick-up Order
// Pick Up Order
// Take Out
// Advance Order
//
// Database standard:
// Advance Order

$isDineIn =
    stripos($order_type, 'dine') !== false;

$isPickUp =
    stripos($order_type, 'pick') !== false ||
    stripos($order_type, 'take out') !== false ||
    stripos($order_type, 'takeout') !== false ||
    stripos($order_type, 'advance') !== false;

if ($isDineIn) {

    $order_type = "Dine In";

} elseif ($isPickUp) {

    $order_type = "Advance Order";

} else {

    jsonErrorBH(
        "Invalid order type. Please select Dine In or Pick-up Order."
    );
}

// ==========================================================
// PICK-UP REQUIRES LOGIN
// ==========================================================

if ($isPickUp && $user_id === null) {

    jsonErrorBH(
        "Please log in before placing a Pick-up Order.",
        [
            "requires_login" => true
        ]
    );
}

// ==========================================================
// VALIDATE ITEMS
// ==========================================================

if (!is_array($items) || count($items) === 0) {
    jsonErrorBH("Your cart is empty.");
}

// ==========================================================
// DATABASE COLUMN DETECTION
// ==========================================================

// Products
$productStockColumn = findColumnBH(
    $conn,
    "products",
    [
        "stock",
        "current_stock",
        "quantity",
        "available_stock"
    ]
);

// Ingredients
$hasIngredients =
    tableExistsBH($conn, "ingredients");

$ingredientStockColumn = findColumnBH(
    $conn,
    "ingredients",
    [
        "current_stock",
        "stock",
        "quantity",
        "available_stock"
    ]
);

$ingredientMinimumColumn = findColumnBH(
    $conn,
    "ingredients",
    [
        "minimum_stock",
        "stock_limit",
        "minimum_quantity"
    ]
);

// Recipes
$hasRecipes =
    tableExistsBH($conn, "recipes");

$recipeProductColumn = findColumnBH(
    $conn,
    "recipes",
    [
        "product_id"
    ]
);

$recipeIngredientColumn = findColumnBH(
    $conn,
    "recipes",
    [
        "ingredient_id"
    ]
);

$recipeRegularColumn = findColumnBH(
    $conn,
    "recipes",
    [
        "regular_qty",
        "quantity",
        "qty",
        "regular_quantity"
    ]
);

$recipeLargeColumn = findColumnBH(
    $conn,
    "recipes",
    [
        "large_qty",
        "large_quantity"
    ]
);

// Supplies
$hasSupplies =
    tableExistsBH($conn, "supplies");

$supplyStockColumn = findColumnBH(
    $conn,
    "supplies",
    [
        "current_stock",
        "stock",
        "quantity",
        "available_stock"
    ]
);

$supplyMinimumColumn = findColumnBH(
    $conn,
    "supplies",
    [
        "minimum_stock",
        "stock_limit",
        "minimum_quantity"
    ]
);

// Product Supplies
$hasProductSupplies =
    tableExistsBH($conn, "product_supplies");

$productSupplyProductColumn = findColumnBH(
    $conn,
    "product_supplies",
    [
        "product_id"
    ]
);

$productSupplySupplyColumn = findColumnBH(
    $conn,
    "product_supplies",
    [
        "supply_id"
    ]
);

$productSupplyRegularColumn = findColumnBH(
    $conn,
    "product_supplies",
    [
        "regular_qty",
        "quantity",
        "qty",
        "regular_quantity"
    ]
);

$productSupplyLargeColumn = findColumnBH(
    $conn,
    "product_supplies",
    [
        "large_qty",
        "large_quantity"
    ]
);

// ==========================================================
// REQUIRED DATABASE STRUCTURE CHECK
// ==========================================================

if (!$hasRecipes ||
    $recipeProductColumn === null ||
    $recipeIngredientColumn === null ||
    $recipeRegularColumn === null
) {
    jsonErrorBH(
        "Recipe configuration is incomplete."
    );
}

if (!$hasIngredients ||
    $ingredientStockColumn === null
) {
    jsonErrorBH(
        "Ingredient inventory configuration is incomplete."
    );
}

// ==========================================================
// VALIDATE ALL ITEMS BEFORE CREATING ORDER
// ==========================================================
//
// IMPORTANT:
// We validate FIRST.
// Only after every item passes validation do we INSERT
// the order.
//
// This prevents an unavailable product from creating
// an order in the database.
// ==========================================================

try {

    /*
     * Keep a product/size quantity summary.
     *
     * Example:
     * Product 5 Regular x2
     * Product 5 Regular x1
     *
     * becomes:
     * Product 5 Regular x3
     *
     * This prevents duplicate cart items from bypassing
     * stock validation.
     */
    $productSizeTotals = [];

    foreach ($items as $item) {

        $product_id = isset($item['product_id'])
            ? (int)$item['product_id']
            : 0;

        $quantity = isset($item['quantity'])
            ? (int)$item['quantity']
            : 0;

        $size = normalizeSizeBH(
            $item['size'] ?? 'Regular'
        );

        if ($product_id <= 0) {
            jsonErrorBH(
                "Invalid product ID."
            );
        }

        if ($quantity <= 0) {
            jsonErrorBH(
                "Invalid product quantity."
            );
        }

        if ($quantity > MAX_PRODUCT_QUANTITY_BH) {
            jsonErrorBH(
                "Maximum order quantity is " .
                MAX_PRODUCT_QUANTITY_BH .
                " per product."
            );
        }

        $key =
            $product_id . "_" . $size;

        if (!isset($productSizeTotals[$key])) {
            $productSizeTotals[$key] = [
                "product_id" => $product_id,
                "size" => $size,
                "quantity" => 0
            ];
        }

        $productSizeTotals[$key]["quantity"] += $quantity;

        if (
            $productSizeTotals[$key]["quantity"] >
            MAX_PRODUCT_QUANTITY_BH
        ) {
            jsonErrorBH(
                "Maximum order quantity is " .
                MAX_PRODUCT_QUANTITY_BH .
                " per product."
            );
        }
    }

    // ======================================================
    // VALIDATE EACH PRODUCT/SIZE
    // ======================================================

    // Combined ingredient requirements for the whole cart.
    $ingredientRequirements = [];

    foreach ($productSizeTotals as $entry) {

        $productId =
            (int)$entry["product_id"];

        $size =
            $entry["size"];

        $requestedQuantity =
            (int)$entry["quantity"];

        // --------------------------------------------------
        // PRODUCT
        // --------------------------------------------------

        $productResult = mysqli_query(
            $conn,
            "
            SELECT *
            FROM products
            WHERE id = $productId
            LIMIT 1
            "
        );

        if (!$productResult) {
            throw new Exception(
                "Unable to check product availability."
            );
        }

        $product =
            mysqli_fetch_assoc(
                $productResult
            );

        mysqli_free_result(
            $productResult
        );

        if (!$product) {
            throw new Exception(
                "Product #$productId was not found."
            );
        }

        // --------------------------------------------------
        // SERVER-AUTHORITATIVE PRICE
        // --------------------------------------------------
        // Regular/Large are actual prices from products.
        // There is NO additional size charge.
        $regularPrice = isset($product['regular_price'])
            ? (float)$product['regular_price']
            : (isset($product['price']) ? (float)$product['price'] : 0.0);

        $largePrice = isset($product['large_price'])
            ? (float)$product['large_price']
            : 0.0;

        if ($size === 'large') {
            if ($largePrice <= 0) {
                throw new Exception(
                    "Large size is not available for this product."
                );
            }
            $price = $largePrice;
        } else {
            $price = $regularPrice;
        }

        if ($price <= 0) {
            throw new Exception(
                "Invalid product price configuration."
            );
        }

        // Authoritative base-price total. Add-ons are handled in the order-item
        // record; their catalog cannot be validated here without a confirmed
        // add-on schema.
        $total += $price * $requestedQuantity;

        // --------------------------------------------------
        // PRODUCT STOCK
        // --------------------------------------------------

        if ($productStockColumn !== null) {

            $productStock =
                qtyBH(
                    $product[$productStockColumn] ?? 0
                );

            if ($productStock <= 0) {

                throw new Exception(
                    "The selected product is currently not available."
                );
            }

            if ($productStock < $requestedQuantity) {

                throw new Exception(
                    "Only " .
                    (int)$productStock .
                    " stock is available for the selected product."
                );
            }
        }

        // --------------------------------------------------
        // INGREDIENT RECIPE CHECK
        // --------------------------------------------------
        //
        // Collect requirements for the ENTIRE cart first.
        // This is important when two products use the same ingredient.
        // Example:
        //   Product A needs Milk x3
        //   Product B needs Milk x4
        //   Cart requirement = Milk x7
        //
        // We validate the combined requirement after collecting all
        // products, preventing the same ingredient from being checked
        // independently and accidentally passing.

        $recipeSizeColumn =
            $size === 'large' &&
            $recipeLargeColumn !== null
                ? $recipeLargeColumn
                : $recipeRegularColumn;

        $recipeSql = "
            SELECT
                r.`$recipeIngredientColumn` AS ingredient_id,
                r.`$recipeSizeColumn` AS required_qty
            FROM recipes r
            WHERE r.`$recipeProductColumn` = $productId
        ";

        $recipeResult = mysqli_query($conn, $recipeSql);

        if (!$recipeResult) {
            throw new Exception(
                "Unable to check recipe ingredients."
            );
        }

        while ($recipe = mysqli_fetch_assoc($recipeResult)) {
            $ingredientId = (int)($recipe["ingredient_id"] ?? 0);

            $requiredPerProduct = qtyBH(
                $recipe["required_qty"] ?? 0
            );

            if ($ingredientId <= 0 || $requiredPerProduct <= 0) {
                continue;
            }

            $requiredTotal =
                $requiredPerProduct * $requestedQuantity;

            if (!isset($ingredientRequirements[$ingredientId])) {
                $ingredientRequirements[$ingredientId] = 0;
            }

            $ingredientRequirements[$ingredientId] += $requiredTotal;
        }

        mysqli_free_result($recipeResult);

        // --------------------------------------------------
        // SUPPLY CHECK
        // --------------------------------------------------

        if (
            $hasProductSupplies &&
            $productSupplyProductColumn !== null &&
            $productSupplySupplyColumn !== null &&
            $productSupplyRegularColumn !== null &&
            $hasSupplies &&
            $supplyStockColumn !== null
        ) {

            $supplySizeColumn =
                $size === 'large' &&
                $productSupplyLargeColumn !== null
                    ? $productSupplyLargeColumn
                    : $productSupplyRegularColumn;

            $supplySql = "
                SELECT
                    ps.`$productSupplySupplyColumn`
                        AS supply_id,
                    ps.`$supplySizeColumn`
                        AS required_qty
                FROM product_supplies ps
                WHERE ps.`$productSupplyProductColumn`
                    = $productId
            ";

            $supplyResult =
                mysqli_query(
                    $conn,
                    $supplySql
                );

            if (!$supplyResult) {
                throw new Exception(
                    "Unable to check product supplies."
                );
            }

            while (
                $supply =
                mysqli_fetch_assoc($supplyResult)
            ) {

                $supplyId =
                    (int)($supply["supply_id"] ?? 0);

                $requiredPerProduct =
                    qtyBH(
                        $supply["required_qty"] ?? 0
                    );

                if (
                    $supplyId <= 0 ||
                    $requiredPerProduct <= 0
                ) {
                    continue;
                }

                $requiredTotal =
                    $requiredPerProduct *
                    $requestedQuantity;

                // Minimum stock
                $minimumSql = "0";

                if ($supplyMinimumColumn !== null) {
                    $minimumSql =
                        "`$supplyMinimumColumn`";
                }

                $supplyStockResult =
                    mysqli_query(
                        $conn,
                        "
                        SELECT
                            `$supplyStockColumn`
                                AS current_stock,
                            COALESCE(
                                $minimumSql,
                                0
                            ) AS minimum_stock
                        FROM supplies
                        WHERE id = $supplyId
                        LIMIT 1
                        "
                    );

                if (!$supplyStockResult) {
                    throw new Exception(
                        "Unable to check supply inventory."
                    );
                }

                $supplyStock =
                    mysqli_fetch_assoc(
                        $supplyStockResult
                    );

                mysqli_free_result(
                    $supplyStockResult
                );

                if (!$supplyStock) {
                    throw new Exception(
                        "Required supply is missing from inventory."
                    );
                }

                $currentStock =
                    qtyBH(
                        $supplyStock["current_stock"]
                    );

                $minimumStock =
                    qtyBH(
                        $supplyStock["minimum_stock"]
                    );

                // ------------------------------------------------
                // LOW SUPPLY = NOT AVAILABLE
                // ------------------------------------------------

                if ($currentStock <= $minimumStock) {

                    throw new Exception(
                        "A required supply is low in stock. " .
                        "The selected product is currently not available."
                    );
                }

                // ------------------------------------------------
                // NOT ENOUGH SUPPLY
                // ------------------------------------------------

                if ($currentStock < $requiredTotal) {

                    throw new Exception(
                        "There is not enough supply stock " .
                        "for the selected product."
                    );
                }
            }

            mysqli_free_result(
                $supplyResult
            );
        }
    }

    // ======================================================
    // VALIDATE COMBINED INGREDIENT REQUIREMENTS
    // ======================================================

    foreach ($ingredientRequirements as $ingredientId => $requiredTotal) {

        $ingredientId = (int)$ingredientId;
        $requiredTotal = qtyBH($requiredTotal);

        if ($ingredientId <= 0 || $requiredTotal <= 0) {
            continue;
        }

        $minimumSql = "0";

        if ($ingredientMinimumColumn !== null) {
            $minimumSql = "`$ingredientMinimumColumn`";
        }

        $ingredientResult = mysqli_query(
            $conn,
            "
            SELECT
                `$ingredientStockColumn` AS current_stock,
                COALESCE($minimumSql, 0) AS minimum_stock
            FROM ingredients
            WHERE id = $ingredientId
            LIMIT 1
            "
        );

        if (!$ingredientResult) {
            throw new Exception(
                "Unable to check ingredient inventory."
            );
        }

        $ingredient = mysqli_fetch_assoc($ingredientResult);

        mysqli_free_result($ingredientResult);

        if (!$ingredient) {
            throw new Exception(
                "Required ingredient #$ingredientId is missing from inventory."
            );
        }

        $currentStock = qtyBH($ingredient["current_stock"]);
        $minimumStock = qtyBH($ingredient["minimum_stock"]);

        // Minimum stock is a safety threshold: once stock reaches
        // the minimum, products using it are unavailable.
        if ($currentStock <= $minimumStock) {
            throw new Exception(
                "A required ingredient (ID #$ingredientId) is low in stock. " .
                "Available: " . (int)$currentStock .
                ". Minimum: " . (int)$minimumStock .
                ". The selected product is currently not available."
            );
        }

        if ($currentStock < $requiredTotal) {
            throw new Exception(
                "There is not enough ingredient stock for the selected product. " .
                "Ingredient ID #$ingredientId: available " .
                (int)$currentStock .
                ", required " .
                (int)$requiredTotal .
                "."
            );
        }
    }

    // ======================================================
    // START TRANSACTION
    // ======================================================

    mysqli_begin_transaction($conn);

    // ======================================================
    // INSERT ORDER
    // ======================================================

    $hasFcmToken =
        columnExistsBH(
            $conn,
            "orders",
            "fcm_token"
        );

    if ($user_id === null) {

        // --------------------------------------------------
        // GUEST DINE-IN
        // --------------------------------------------------

        if ($hasFcmToken) {

            $stmt = mysqli_prepare(
                $conn,
                "
                INSERT INTO orders
                (
                    user_id,
                    order_type,
                    total,
                    payment_method,
                    payment_type,
                    paid_amount,
                    balance,
                    receipt_number,
                    fcm_token
                )
                VALUES
                (
                    NULL,
                    ?,
                    ?,
                    ?,
                    ?,
                    ?,
                    ?,
                    ?,
                    ?
                )
                "
            );

            if (!$stmt) {
                throw new Exception(
                    "Failed to prepare order: " .
                    mysqli_error($conn)
                );
            }

            mysqli_stmt_bind_param(
                $stmt,
                "sdssddss",
                $order_type,
                $total,
                $payment_method,
                $payment_type,
                $paid_amount,
                $balance,
                $receipt_number,
                $fcm_token
            );

        } else {

            $stmt = mysqli_prepare(
                $conn,
                "
                INSERT INTO orders
                (
                    user_id,
                    order_type,
                    total,
                    payment_method,
                    payment_type,
                    paid_amount,
                    balance,
                    receipt_number
                )
                VALUES
                (
                    NULL,
                    ?,
                    ?,
                    ?,
                    ?,
                    ?,
                    ?,
                    ?
                )
                "
            );

            if (!$stmt) {
                throw new Exception(
                    "Failed to prepare order: " .
                    mysqli_error($conn)
                );
            }

            mysqli_stmt_bind_param(
                $stmt,
                "sdssdds",
                $order_type,
                $total,
                $payment_method,
                $payment_type,
                $paid_amount,
                $balance,
                $receipt_number
            );
        }

    } else {

        // --------------------------------------------------
        // LOGGED-IN USER
        // --------------------------------------------------

        if ($hasFcmToken) {

            $stmt = mysqli_prepare(
                $conn,
                "
                INSERT INTO orders
                (
                    user_id,
                    order_type,
                    total,
                    payment_method,
                    payment_type,
                    paid_amount,
                    balance,
                    receipt_number,
                    fcm_token
                )
                VALUES
                (
                    ?,
                    ?,
                    ?,
                    ?,
                    ?,
                    ?,
                    ?,
                    ?,
                    ?
                )
                "
            );

            if (!$stmt) {
                throw new Exception(
                    "Failed to prepare order: " .
                    mysqli_error($conn)
                );
            }

            mysqli_stmt_bind_param(
                $stmt,
                "isdssddss",
                $user_id,
                $order_type,
                $total,
                $payment_method,
                $payment_type,
                $paid_amount,
                $balance,
                $receipt_number,
                $fcm_token
            );

        } else {

            $stmt = mysqli_prepare(
                $conn,
                "
                INSERT INTO orders
                (
                    user_id,
                    order_type,
                    total,
                    payment_method,
                    payment_type,
                    paid_amount,
                    balance,
                    receipt_number
                )
                VALUES
                (
                    ?,
                    ?,
                    ?,
                    ?,
                    ?,
                    ?,
                    ?,
                    ?
                )
                "
            );

            if (!$stmt) {
                throw new Exception(
                    "Failed to prepare order: " .
                    mysqli_error($conn)
                );
            }

            mysqli_stmt_bind_param(
                $stmt,
                "isdssdds",
                $user_id,
                $order_type,
                $total,
                $payment_method,
                $payment_type,
                $paid_amount,
                $balance,
                $receipt_number
            );
        }
    }

    // ======================================================
    // EXECUTE ORDER
    // ======================================================

    if (!mysqli_stmt_execute($stmt)) {
        throw new Exception(
            "Failed to create order: " .
            mysqli_stmt_error($stmt)
        );
    }

    $order_id =
        mysqli_insert_id($conn);

    // Canonical Black Habit order/receipt number.
    $receipt_number = "BH-" . date("Y") . "-" . str_pad(
        (string)$order_id,
        6,
        "0",
        STR_PAD_LEFT
    );

    // Save the server-generated receipt number.
    if (!columnExistsBH($conn, "orders", "receipt_number")) {
        throw new Exception(
            "Orders table is missing the receipt_number column."
        );
    }

    $receiptUpdate = mysqli_prepare(
        $conn,
        "UPDATE orders
         SET receipt_number = ?
         WHERE id = ?
         LIMIT 1"
    );

    if (!$receiptUpdate) {
        throw new Exception(
            "Failed to prepare receipt number update: " .
            mysqli_error($conn)
        );
    }

    mysqli_stmt_bind_param(
        $receiptUpdate,
        "si",
        $receipt_number,
        $order_id
    );

    if (!mysqli_stmt_execute($receiptUpdate)) {
        throw new Exception(
            "Failed to save receipt number: " .
            mysqli_stmt_error($receiptUpdate)
        );
    }

    mysqli_stmt_close($receiptUpdate);

    mysqli_stmt_close($stmt);

    // ======================================================
    // ORDER ITEM COLUMNS
    // ======================================================

    $hasCategory =
        columnExistsBH(
            $conn,
            "order_items",
            "category"
        );

    $hasAddons =
        columnExistsBH(
            $conn,
            "order_items",
            "addons"
        );

    $hasAddonsPrice =
        columnExistsBH(
            $conn,
            "order_items",
            "addons_price"
        );

    $hasSizePrice =
        columnExistsBH(
            $conn,
            "order_items",
            "size_price"
        );

    $hasSpecialInstructions =
        columnExistsBH(
            $conn,
            "order_items",
            "special_instructions"
        );

    // ======================================================
    // INSERT ORDER ITEMS
    // ======================================================

    foreach ($items as $item) {

        $product_id =
            isset($item['product_id'])
                ? (int)$item['product_id']
                : 0;

        $quantity =
            isset($item['quantity'])
                ? (int)$item['quantity']
                : 0;

        // Server-authoritative base price.
        // Regular and Large are separate database prices; no size surcharge.
        $price = 0.0;

        $flavor =
            trim(
                (string)($item['flavor'] ?? '')
            );

        $size =
            trim(
                (string)($item['size'] ?? 'Regular')
            );

        $size = displaySizeBH($size);

        $sugar =
            trim(
                (string)($item['sugar'] ?? '')
            );

        $ice =
            trim(
                (string)($item['ice'] ?? '')
            );

        $category =
            trim(
                (string)($item['category'] ?? '')
            );

        $addons =
            trim(
                (string)($item['addons'] ?? '')
            );

        $addons_price =
            isset($item['addons_price'])
                ? (float)$item['addons_price']
                : 0;

        // Size is already included in the selected $price.
        // There is NO separate size surcharge.
        $size_price = 0.0;

        $special_instructions =
            trim(
                (string)(
                    $item['special_instructions'] ?? ''
                )
            );

        if ($product_id <= 0) {
            throw new Exception(
                "Invalid product ID."
            );
        }

        if ($quantity <= 0) {
            throw new Exception(
                "Invalid product quantity."
            );
        }

        if ($quantity > MAX_PRODUCT_QUANTITY_BH) {
            throw new Exception(
                "Maximum order quantity is " .
                MAX_PRODUCT_QUANTITY_BH .
                " per product."
            );
        }

        // --------------------------------------------------
        // SERVER-AUTHORITATIVE ITEM PRICE
        // --------------------------------------------------

        $itemProductResult = mysqli_query(
            $conn,
            "SELECT regular_price, large_price
             FROM products
             WHERE id = $product_id
             LIMIT 1"
        );

        if (!$itemProductResult) {
            throw new Exception(
                "Unable to verify product price."
            );
        }

        $itemProduct = mysqli_fetch_assoc($itemProductResult);
        mysqli_free_result($itemProductResult);

        if (!$itemProduct) {
            throw new Exception(
                "Product #$product_id was not found."
            );
        }

        $regularPrice = isset($itemProduct['regular_price'])
            ? (float)$itemProduct['regular_price']
            : 0.0;

        $largePrice = isset($itemProduct['large_price'])
            ? (float)$itemProduct['large_price']
            : 0.0;

        if (normalizeSizeBH($size) === 'large') {
            if ($largePrice <= 0) {
                throw new Exception(
                    "Large size is not available for this product."
                );
            }

            $price = $largePrice;
        } else {
            if ($regularPrice <= 0) {
                throw new Exception(
                    "Invalid product price configuration."
                );
            }

            $price = $regularPrice;
        }

        // Add-on price is stored separately when the schema supports it.
        // The API does not assume a specific add-on table/schema.
        if ($addons_price < 0) {
            throw new Exception("Invalid add-on price.");
        }

        // --------------------------------------------------
        // Build dynamic INSERT
        // --------------------------------------------------

        $columns = [
            "order_id",
            "product_id",
            "quantity",
            "price",
            "flavor",
            "size",
            "sugar",
            "ice"
        ];

        $placeholders = [
            "?",
            "?",
            "?",
            "?",
            "?",
            "?",
            "?",
            "?"
        ];

        $types = "iiidssss";

        $values = [
            $order_id,
            $product_id,
            $quantity,
            $price,
            $flavor,
            $size,
            $sugar,
            $ice
        ];

        // category
        if ($hasCategory) {

            $columns[] =
                "category";

            $placeholders[] =
                "?";

            $types .= "s";

            $values[] =
                $category;
        }

        // addons
        if ($hasAddons) {

            $columns[] =
                "addons";

            $placeholders[] =
                "?";

            $types .= "s";

            $values[] =
                $addons;
        }

        // addons_price
        if ($hasAddonsPrice) {

            $columns[] =
                "addons_price";

            $placeholders[] =
                "?";

            $types .= "d";

            $values[] =
                $addons_price;
        }

        // size_price
        if ($hasSizePrice) {

            $columns[] =
                "size_price";

            $placeholders[] =
                "?";

            $types .= "d";

            $values[] =
                $size_price;
        }

        // special instructions
        if ($hasSpecialInstructions) {

            $columns[] =
                "special_instructions";

            $placeholders[] =
                "?";

            $types .= "s";

            $values[] =
                $special_instructions;
        }

        $columnSql =
            implode(
                ", ",
                $columns
            );

        $placeholderSql =
            implode(
                ", ",
                $placeholders
            );

        $itemSql =
            "
            INSERT INTO order_items
            (
                $columnSql
            )
            VALUES
            (
                $placeholderSql
            )
            ";

        $itemStmt =
            mysqli_prepare(
                $conn,
                $itemSql
            );

        if (!$itemStmt) {
            throw new Exception(
                "Failed to prepare order item: " .
                mysqli_error($conn)
            );
        }

        // --------------------------------------------------
        // Dynamic bind_param
        // --------------------------------------------------

        $bindValues = [];

        $bindValues[] =
            $types;

        foreach ($values as $key => $value) {
            $bindValues[] =
                &$values[$key];
        }

        call_user_func_array(
            [
                $itemStmt,
                'bind_param'
            ],
            $bindValues
        );

        if (!mysqli_stmt_execute($itemStmt)) {
            throw new Exception(
                "Failed to save order item: " .
                mysqli_stmt_error($itemStmt)
            );
        }

        mysqli_stmt_close(
            $itemStmt
        );
    }

    // ======================================================
    // FINAL SERVER TOTAL
    // ======================================================

    // Include the add-on amounts actually stored with each order item.
    // Base prices remain server-authoritative.
    $finalTotal = 0.0;

    // IMPORTANT:
    // Some Black Habit databases do NOT have an addons_price column
    // in order_items. Only select it when the column actually exists.
    if ($hasAddonsPrice) {

        $finalItemsResult = mysqli_query(
            $conn,
            "SELECT quantity, price, addons_price
             FROM order_items
             WHERE order_id = " . (int)$order_id
        );

    } else {

        $finalItemsResult = mysqli_query(
            $conn,
            "SELECT quantity, price
             FROM order_items
             WHERE order_id = " . (int)$order_id
        );
    }

    if (!$finalItemsResult) {
        throw new Exception(
            "Unable to calculate final order total: " .
            mysqli_error($conn)
        );
    }

    while ($finalItem = mysqli_fetch_assoc($finalItemsResult)) {

        $finalQty = (int)($finalItem['quantity'] ?? 0);

        $finalPrice =
            (float)($finalItem['price'] ?? 0);

        $finalAddonPrice = 0.0;

        if ($hasAddonsPrice) {
            $finalAddonPrice =
                (float)($finalItem['addons_price'] ?? 0);
        }

        if ($finalAddonPrice < 0) {
            $finalAddonPrice = 0;
        }

        $finalTotal +=
            ($finalPrice + $finalAddonPrice) * $finalQty;
    }

    mysqli_free_result($finalItemsResult);

    $finalTotal = round($finalTotal, 2);

    $finalTotalStmt = mysqli_prepare(
        $conn,
        "UPDATE orders
         SET total = ?
         WHERE id = ?
         LIMIT 1"
    );

    if (!$finalTotalStmt) {
        throw new Exception(
            "Failed to prepare final order total update: " .
            mysqli_error($conn)
        );
    }

    mysqli_stmt_bind_param(
        $finalTotalStmt,
        "di",
        $finalTotal,
        $order_id
    );

    if (!mysqli_stmt_execute($finalTotalStmt)) {
        throw new Exception(
            "Failed to save final order total: " .
            mysqli_stmt_error($finalTotalStmt)
        );
    }

    mysqli_stmt_close($finalTotalStmt);

    $total = $finalTotal;

    // ======================================================
    // COMMIT
    // ======================================================

    mysqli_commit($conn);

    // ======================================================
    // SUCCESS
    // ======================================================

    echo json_encode(
        [
            "success" => true,
            "message" =>
                "Order placed successfully.",
            "order_id" =>
                (int)$order_id,
            "receipt_number" =>
                $receipt_number,
            "order_type" =>
                $order_type,
            "display_order_type" =>
                $isPickUp
                    ? "Pick-up Order"
                    : "Dine In",
            "user_id" =>
                $user_id
        ],
        JSON_UNESCAPED_UNICODE |
        JSON_UNESCAPED_SLASHES
    );

} catch (Throwable $e) {

    // ======================================================
    // ROLLBACK
    // ======================================================

    mysqli_rollback($conn);

    error_log(
        "BLACK HABIT CREATE ORDER ERROR: " .
        $e->getMessage()
    );

    echo json_encode(
        [
            "success" => false,
            "message" =>
                $e->getMessage()
        ],
        JSON_UNESCAPED_UNICODE |
        JSON_UNESCAPED_SLASHES
    );
}

mysqli_close($conn);

?>